# Default conf.rb attributes file, generated by fhcap, do not edit

include_attribute 'feedhenry_common'
default['fh-appstore']['conf']['coreUrl'] = "RECIPE_OVERRIDE"
default['fh-appstore']['conf']['environment'] = "RECIPE_OVERRIDE"
default['fh-appstore']['conf']['https']['enabled'] = false
default['fh-appstore']['conf']['logger'] = "RECIPE_OVERRIDE"
default['fh-appstore']['conf']['port'] = 8821
default['fh-appstore']['conf']['rootUrl'] = "/"
