# Default conf.rb attributes file, generated by fhcap, do not edit

include_attribute 'feedhenry_common'
default['fh-dataman']['conf']['coreUrl'] = "RECIPE_OVERRIDE"
default['fh-dataman']['conf']['environment'] = "RECIPE_OVERRIDE"
default['fh-dataman']['conf']['https']['enabled'] = false
default['fh-dataman']['conf']['logger'] = "RECIPE_OVERRIDE"
default['fh-dataman']['conf']['port'] = 44444
default['fh-dataman']['conf']['rootUrl'] = "/"
